name: Production Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  version: ${{ github.ref_name }}
  build_folder: './build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Generate version.txt
        run: echo "$version" > "${build_folder}/version.txt"

      - name: Pack project
        run: npm run zip

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: access8math-web-template.zip
